name: dbt CI

on:
  pull_request:
    branches:
      - main

jobs:
  dbt_test:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_PRIVATE_KEY_PATH_DEV: /tmp/snowflake_rsa_key.p8

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Write Snowflake private key
        run: |
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > /tmp/snowflake_rsa_key.p8

      - name: dbt deps
        run: dbt deps --profiles-dir ./profiles
        working-directory: ./dbt

      - name: dbt test
        run: dbt test --target snowflake_iceberg --profiles-dir ./profiles
        working-directory: ./dbt